import { Router } from 'express';
import { prisma } from '../db/client.js';
import { authMiddleware } from '../middleware/auth.js';
const router = Router();
async function githubJson(url, init) {
    const response = await fetch(url, init);
    if (!response.ok) {
        const errorBody = await response.json().catch(() => ({}));
        throw new Error(errorBody.message || `GitHub request failed: ${response.status}`);
    }
    return response.json();
}
function parseProjectFiles(content, projectFiles) {
    if (Array.isArray(projectFiles) && projectFiles.length > 0) {
        return projectFiles.filter(file => file?.path && typeof file.content === 'string');
    }
    try {
        const parsed = JSON.parse(content);
        if (Array.isArray(parsed) && parsed.length > 0 && parsed[0]?.path) {
            return parsed.filter(file => file?.path && typeof file.content === 'string');
        }
    }
    catch {
        // Not JSON; caller will fall back to single-file push
    }
    return [];
}
/**
 * POST /api/github/push - Push deliverable to a GitHub repo (supports single HTML and multi-file projects)
 */
router.post('/push', authMiddleware, async (req, res) => {
    try {
        const userId = req.auth.userId;
        const { deliverableId, repoName, commitMessage, createNew, files: projectFiles } = req.body;
        if (!deliverableId || !repoName) {
            return res.status(400).json({ error: 'deliverableId and repoName are required' });
        }
        const user = await prisma.user.findUnique({ where: { id: userId } });
        if (!user?.githubToken) {
            return res.status(400).json({ error: 'GitHub token not configured. Set it in Settings.' });
        }
        const deliverable = await prisma.deliverable.findUnique({ where: { id: deliverableId } });
        if (!deliverable) {
            return res.status(404).json({ error: 'Deliverable not found' });
        }
        const headers = {
            Authorization: `token ${user.githubToken}`,
            Accept: 'application/vnd.github.v3+json',
            'Content-Type': 'application/json',
        };
        let ghUser;
        try {
            ghUser = await githubJson('https://api.github.com/user', { headers });
        }
        catch {
            return res.status(401).json({ error: 'GitHub token is invalid or expired' });
        }
        const owner = ghUser.login;
        if (createNew) {
            try {
                await githubJson('https://api.github.com/user/repos', {
                    method: 'POST',
                    headers,
                    body: JSON.stringify({
                        name: repoName,
                        description: `Generated by Plury - ${deliverable.title}`,
                        private: false,
                        auto_init: true,
                    }),
                });
            }
            catch (error) {
                const message = error instanceof Error ? error.message : 'Failed to create repo';
                if (!message.includes('already exists')) {
                    return res.status(400).json({ error: `Failed to create repo: ${message}` });
                }
            }
            await new Promise(resolve => setTimeout(resolve, 1500));
        }
        const message = commitMessage || `Update from Plury: ${deliverable.title}`;
        const files = parseProjectFiles(deliverable.content, projectFiles);
        if (files.length > 0) {
            await pushMultiFile(owner, repoName, files, message, headers);
        }
        else {
            await pushSingleFile(owner, repoName, 'index.html', deliverable.content, message, headers);
        }
        const readmeContent = `# ${deliverable.title}\n\nGenerated by [Plury](https://plury.co)\n\nAgent: ${deliverable.agent}\n`;
        await pushSingleFile(owner, repoName, 'README.md', readmeContent, 'Update README', headers);
        res.json({
            success: true,
            repoUrl: `https://github.com/${owner}/${repoName}`,
            owner,
            repo: repoName,
            fileCount: files.length > 0 ? files.length : 1,
        });
    }
    catch (error) {
        console.error('[GitHub Push] Error:', error);
        const message = error instanceof Error ? error.message : 'Failed to push to GitHub';
        res.status(500).json({ error: message });
    }
});
async function pushSingleFile(owner, repo, filePath, content, message, headers) {
    const encoded = Buffer.from(content).toString('base64');
    let sha;
    const existingResp = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`, { headers });
    if (existingResp.ok) {
        const existing = await existingResp.json();
        sha = existing.sha;
    }
    await githubJson(`https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`, {
        method: 'PUT',
        headers,
        body: JSON.stringify({
            message,
            content: encoded,
            ...(sha ? { sha } : {}),
        }),
    });
}
async function pushMultiFile(owner, repo, files, message, headers) {
    const baseUrl = `https://api.github.com/repos/${owner}/${repo}`;
    const repoMeta = await githubJson(baseUrl, { headers });
    const branch = repoMeta.default_branch || 'main';
    const ref = await githubJson(`${baseUrl}/git/ref/heads/${branch}`, { headers });
    const latestCommitSha = ref.object.sha;
    const commit = await githubJson(`${baseUrl}/git/commits/${latestCommitSha}`, { headers });
    const baseTreeSha = commit.tree.sha;
    const treeItems = await Promise.all(files.map(async (file) => {
        const blob = await githubJson(`${baseUrl}/git/blobs`, {
            method: 'POST',
            headers,
            body: JSON.stringify({
                content: file.content,
                encoding: 'utf-8',
            }),
        });
        return {
            path: file.path,
            mode: '100644',
            type: 'blob',
            sha: blob.sha,
        };
    }));
    const tree = await githubJson(`${baseUrl}/git/trees`, {
        method: 'POST',
        headers,
        body: JSON.stringify({
            base_tree: baseTreeSha,
            tree: treeItems,
        }),
    });
    const newCommit = await githubJson(`${baseUrl}/git/commits`, {
        method: 'POST',
        headers,
        body: JSON.stringify({
            message,
            tree: tree.sha,
            parents: [latestCommitSha],
        }),
    });
    await githubJson(`${baseUrl}/git/refs/heads/${branch}`, {
        method: 'PATCH',
        headers,
        body: JSON.stringify({ sha: newCommit.sha }),
    });
}
/**
 * POST /api/github/validate - Validate a GitHub token
 */
router.post('/validate', authMiddleware, async (req, res) => {
    try {
        const { token } = req.body;
        if (!token)
            return res.status(400).json({ error: 'Token required' });
        const response = await fetch('https://api.github.com/user', {
            headers: {
                Authorization: `token ${token}`,
                Accept: 'application/vnd.github.v3+json',
            },
        });
        if (!response.ok) {
            return res.json({ valid: false });
        }
        const user = await response.json();
        res.json({ valid: true, username: user.login, avatarUrl: user.avatar_url });
    }
    catch {
        res.json({ valid: false });
    }
});
/**
 * POST /api/github/save-token - Save GitHub token for user
 */
router.post('/save-token', authMiddleware, async (req, res) => {
    try {
        const userId = req.auth.userId;
        const { token } = req.body;
        await prisma.user.update({
            where: { id: userId },
            data: { githubToken: token || null },
        });
        res.json({ success: true });
    }
    catch (error) {
        console.error('[GitHub] Error saving token:', error);
        res.status(500).json({ error: 'Failed to save token' });
    }
});
export default router;
//# sourceMappingURL=github.js.map